language: rust
sudo: required

matrix:
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-unknown-linux-gnu
  - os: linux
    rust: stable
    env: TARGET=i686-unknown-linux-gnu

install:
- ci/install.sh
script:
- ci/build.sh
